import "./globals.css";

import type { Metadata } from "next";
import { Inter } from "next/font/google";

import Header from "../components/layout/header";
import HeaderMobile from "../components/layout/header-mobile";
import MarginWidthWrapper from "../components/layout/margin-width-wrapper";
import PageWrapper from "../components/layout/page-wrapper";
import SideNav from "../components/layout/side-nav";
import { Providers } from "./providers";
import { Toaster } from "sonner";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Ai assistant",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body className={`bg-white${inter.className}`}>
				<div className="flex">
					<SideNav />
					<main className="flex-1">
						<MarginWidthWrapper>
							<Header />
							<HeaderMobile />
							<PageWrapper>
								<Providers>{children}</Providers>
							</PageWrapper>
						</MarginWidthWrapper>
						<Toaster closeButton richColors position="top-right"/>
					</main>
				</div>
			</body>
		</html>
	);
}